-- NOTE: twoslash-queries.nvim is not available in nixpkgs
-- Original config was:
-- require("utils").add_package({ "https://github.com/marilari88/twoslash-queries.nvim", },
--   function()
--     local augroup = vim.api.nvim_create_augroup("twoslash_queries_attach",
--       { clear = true, })
--
--     vim.api.nvim_create_autocmd("LspAttach", {
--       group = augroup,
--       callback = function(event)
--         local bufnr = event.buf
--
--         local client = vim.lsp.get_client_by_id(event.data.client_id)
--         if not client or client.name ~= "ts_ls" then
--           return
--         end
--
--         require("twoslash-queries").attach(client, bufnr)
--       end,
--       pattern = { "*.ts", "*.tsx", },
--     })
--   end)
-- This plugin would need to be packaged for nix or loaded via a different method
-- Keeping this file as a placeholder in case it becomes available in the future
