#!/usr/bin/env bash
# Generate a list of non-nix-managed applications, split by install method.
# Excludes: Nix Apps (nix-darwin), Utilities, Safari, apps nested inside .app bundles,
# and apps with a matching name in Nix Apps/ (duplicates created by installers).
set -euo pipefail

output_file="applications.md"
mas_bin="/run/current-system/sw/bin/mas"

# Collect nix-darwin managed app names for duplicate filtering
declare -A nix_apps
while IFS= read -r app_path; do
  name=$(basename "$app_path" .app)
  nix_apps["$name"]=1
done < <(find /Applications/Nix\ Apps -maxdepth 1 -name "*.app" 2>/dev/null)

# Collect mas-installed app names
declare -A mas_apps
if command -v "$mas_bin" &>/dev/null; then
  while IFS= read -r line; do
    name=$(echo "$line" | sed 's/^[[:space:]]*[0-9]*[[:space:]]*//' | sed 's/[[:space:]]*([^)]*)[[:space:]]*$//')
    mas_apps["$name"]=1
  done < <("$mas_bin" list 2>/dev/null || true)
fi

# Find .app bundles in /Applications, filtering out system/nix stuff
mapfile -t apps < <(
  find /Applications -maxdepth 3 -name "*.app" \
    -not -path "*/Nix Apps/*" \
    -not -path "*/Utilities/*" \
    -not -name "Safari.app" \
    -not -regex ".*\.app/.*/.*\.app" \
    2>/dev/null | sort
)

mas_list=()
other_list=()

for app_path in "${apps[@]}"; do
  app_name=$(basename "$app_path" .app)

  # Skip duplicates of nix-darwin managed apps
  if [[ -v "nix_apps[$app_name]" ]]; then
    continue
  fi

  if [[ -v "mas_apps[$app_name]" ]]; then
    mas_list+=("$app_name")
  else
    other_list+=("$app_name")
  fi
done

{
  echo "# Applications"
  echo ""
  echo 'Non-nix-managed applications. Generated by scripts/generate-app-list.sh.'
  echo ""
  echo "## Mac App Store"
  echo ""
  for app in "${mas_list[@]}"; do
    echo "- $app"
  done
  echo ""
  echo "## Other"
  echo ""
  for app in "${other_list[@]}"; do
    echo "- $app"
  done
} >"$output_file"

echo "Generated $output_file"
